;
with x as(
select Sproc = 'RecipeGet'
union select'RecipeInsert'
union select'RecipeClone'
union select'MealsGet'
union select'CookbooksGet'
union select'CookbookInsert'
union select'CookbookDelete'
union select'CookbooksAuto-Create'
union select'StaffDelete'
union select'StaffInsert'
union select'CuisinesDelete'
union select'CuisinesInsert'
union select'IngredientsDelete'
union select'IngredientsInsert'
union select'MeasurmentsDelete'
union select'MeasurmentsInsert'
union select'CoursesDelete'
union select'CoursesInsert'
union select'RecipeIngredientGet'
union select'RecipeIngredientInsert'
union select'RecipeIngredientDelete'
union select'RecipeDirectionGet'
union select'RecipeDirectionInsert'
union select'RecipeDirectionDelete'
)
select *
from x where Sproc like '%Get'

